export type User = {
  sub: string;
  email: string;
  preferred_username: string;
  groups: string[];
  roles: string[];
  email_verified?: boolean;
  name?: string;
  given_name?: string;
  family_name?: string;
  middle_name?: string;
  nickname?: string;
  profile?: string;
  picture?: string;
  website?: string;
  gender?: string;
  birthdate?: string;
  zoneinfo?: string;
  locale?: string;
  phone_number?: string;
  phone_number_verified?: boolean;
  address?: string;
  device_key?: string;
  updated_at?: string;
};
